### ISSUE TITLE
Handle Plotly bug when running with `--flat` with older versions of pillow

### ISSUE THREAD

**Issue by ewels** [MultiQC/MultiQC#2310]
I get an exception when generating a report with flat image plots, using `--flat`. Example with FastQC test data:

```console
$ multiqc -f  data/modules/fastqc --flat

  /// MultiQC 🔍 | v1.20.dev0 (df8921c)

|           multiqc | Search path : /Users/ewels/GitHub/MultiQC/test-data/data/modules/fastqc
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 65/65
|            fastqc | Couldn't read 'fake_report_fastqc.zip' - Bad zip file
|            fastqc | Found 35 reports
|            fastqc | Sample had zero reads: 'SK-GBD-000919.1'
╭────────────────────────────── Oops! The 'fastqc' MultiQC module broke... ───────────────────────────────╮
│ Please copy this log and report it at https://github.com/MultiQC/MultiQC/issues                         │
│ Please attach a file that triggers the error. The last file found was:                                  │
│ data/modules/fastqc/zero_reads/empty_fastqc.zip                                                         │
│                                                                                                         │
│ Traceback (most recent call last):                                                                      │
│   File "/Users/ewels/GitHub/MultiQC/MultiQC/multiqc/multiqc.py", line 709, in run                       │
│     output = mod()                                                                                      │
│   File "/Users/ewels/GitHub/MultiQC/MultiQC/multiqc/modules/fastqc/fastqc.py", line 130, in __init__    │
│     self.read_count_plot()                                                                              │
│   File "/Users/ewels/GitHub/MultiQC/MultiQC/multiqc/modules/fastqc/fastqc.py", line 396, in read_count_ │
│     plot=bargraph.plot(pdata, pcats, pconfig),                                                          │
│   File "/Users/ewels/GitHub/MultiQC/MultiQC/multiqc/plots/bargraph.py", line 201, in plot               │
│     return bar.plot(plotdata, plotsamples, pconfig)                                                     │
│   File "/Users/ewels/GitHub/MultiQC/MultiQC/multiqc/plots/plotly/bar.py", line 43, in plot              │
│     return p.add_to_report(report)                                                                      │
│   File "/Users/ewels/GitHub/MultiQC/MultiQC/multiqc/plots/plotly/plot.py", line 231, in add_to_report   │
│     html = self.flat_plot()                                                                             │
│   File "/Users/ewels/GitHub/MultiQC/MultiQC/multiqc/plots/plotly/plot.py", line 280, in flat_plot       │
│     html += self._fig_to_static_html(                                                                   │
│   File "/Users/ewels/GitHub/MultiQC/MultiQC/multiqc/plots/plotly/plot.py", line 443, in _fig_to_static_ │
│     img_buffer = Plot.add_logo(img_buffer, format="PNG")                                                │
│   File "/Users/ewels/GitHub/MultiQC/MultiQC/multiqc/plots/plotly/plot.py", line 477, in add_logo        │
│     text_width: float = draw.textlength(text, font_size=font_size)                                      │
│ TypeError: ImageDraw.textlength() got an unexpected keyword argument 'font_size'                        │
│                                                                                                         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "/Users/ewels/.miniconda3/miniconda3/envs/py3.10/bin/multiqc", line 8, in <module>
    sys.exit(run_multiqc())
  File "/Users/ewels/GitHub/MultiQC/MultiQC/multiqc/__main__.py", line 23, in run_multiqc
    multiqc.run_cli(prog_name="multiqc")
  File "/Users/ewels/.miniconda3/miniconda3/envs/py3.10/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ewels/.miniconda3/miniconda3/envs/py3.10/lib/python3.10/site-packages/rich_click/rich_command.py", line 126, in main
    rv = self.invoke(ctx)
  File "/Users/ewels/.miniconda3/miniconda3/envs/py3.10/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ewels/.miniconda3/miniconda3/envs/py3.10/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/ewels/GitHub/MultiQC/MultiQC/multiqc/multiqc.py", line 297, in run_cli
    multiqc_run = run(**kwargs)
  File "/Users/ewels/GitHub/MultiQC/MultiQC/multiqc/multiqc.py", line 927, in run
    report.general_stats_html = table.plot(report.general_stats_data, report.general_stats_headers, pconfig)
  File "/Users/ewels/GitHub/MultiQC/MultiQC/multiqc/plots/table.py", line 58, in plot
    return table.plot(dt)
  File "/Users/ewels/GitHub/MultiQC/MultiQC/multiqc/plots/plotly/table.py", line 14, in plot
    return violin.plot(dt, show_table_by_default=True)
  File "/Users/ewels/GitHub/MultiQC/MultiQC/multiqc/plots/plotly/violin.py", line 26, in plot
    return p.add_to_report(report)
  File "/Users/ewels/GitHub/MultiQC/MultiQC/multiqc/plots/plotly/violin.py", line 419, in add_to_report
    violin_html = super().add_to_report(report)
  File "/Users/ewels/GitHub/MultiQC/MultiQC/multiqc/plots/plotly/plot.py", line 231, in add_to_report
    html = self.flat_plot()
  File "/Users/ewels/GitHub/MultiQC/MultiQC/multiqc/plots/plotly/plot.py", line 280, in flat_plot
    html += self._fig_to_static_html(
  File "/Users/ewels/GitHub/MultiQC/MultiQC/multiqc/plots/plotly/plot.py", line 443, in _fig_to_static_html
    img_buffer = Plot.add_logo(img_buffer, format="PNG")
  File "/Users/ewels/GitHub/MultiQC/MultiQC/multiqc/plots/plotly/plot.py", line 477, in add_logo
    text_width: float = draw.textlength(text, font_size=font_size)
TypeError: ImageDraw.textlength() got an unexpected keyword argument 'font_size'
```

(Not sure why the exception gets printed twice..)

This appears to be due to the version of Pillow that I had installed (9.4.9). When I upgraded to 10.2.0 the error dissapeared and the the code worked fine.

I can't actually find Pillow in `setup.py` or any set of dependencies? But we should pin a minimum version here.

I wonder if we also wrap the `add_logo` function with some pretty generous exception handling, as it's fairly trivial functionality but probably some of the most high risk code in all of MultiQC for failures (as Pillow is a very complex dependency). So could be nice to tolerate import errors and all sorts of others.

**Comment by vladsavelyev** [comment]
Oh, thanks for spotting this issue. Pillow is a dependency to matplotlib, and matplotlib pins it to >=8 (so wonder why the CI didn't catch this 🤔 ): 

```sh
$ pipdeptree -r -p Pillow
Pillow==10.1.0
└── matplotlib==3.8.1 [requires: Pillow>=8]
    └── multiqc==1.20.dev0 [requires: matplotlib>=2.1.1]
```

Added a fix: https://github.com/MultiQC/MultiQC/pull/2312
